### ISSUE TITLE
Conditionally enabling at build time?

### ISSUE THREAD

**Issue by bbarker** [rayon-rs/rayon-macro#3]
I have an odd use case where it would be nice to be able to switch between iter and par_iter at build time, as I am potentially aiming to target a platform without threads. Is this something that can be done with this macro?

Thanks!

**Comment by cuviper** [comment]
In `Cargo.toml`, you can make `rayon-macro` a [platform-specific dependency](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#platform-specific-dependencies), which you might even write in the negative as `cfg(not(threadless target conditions here))`. Then in your source you can use the same condition to either `#[cfg(...)] use rayon_macro::parallel` or else define your own placeholder like:

```rust
macro_rules! parallel {
    // no-op, just pass all tokens without processing
    ($($tokens:tt)*) => { $($tokens)* }
}
```

**Comment by bbarker** [comment]
Thanks! That works amazingly well (my first time using Cargo features and Rust macros and beyond just calling them).

However, in my code, the `parallel!` macro seems to expect `for`:

```
error: expected `for`
   --> src/counting.rs:229:15
    |
229 |     parallel!(b_slice.iter().fold(0_usize, |ac, bt| {
    |               ^^^^^^^
```

Is it possible that macro could be altered to work with calls to `iter()` as well?

**Comment by bbarker** [comment]
Some progress (though I'm no longer using this `rayon-macro`, so feel free to close the issue):

The following macro appears to work for creating the iterator:

```rust
#[macro_export]
macro_rules! par_iter {
    ($($tokens:tt)*) => {{
      #[cfg(feature = "threaded")]
      let itr = $($tokens)*.par_iter();
      #[cfg(not(feature = "threaded"))]
      let itr = $($tokens)*.iter();
      itr
    }}
}
```
However, I then realized that rayon's `fold` is quite different from Iterator`s fold. So now I'm wondering if there is a way to have a macro that transforms a standard Iterator fold into a Rayon fold+reduce generically, so the eventual result is the same in either case.

**Comment by cuviper** [comment]
Right, this macro is purely about converting `for` loops. I think trying to support arbitrary iterator chains would get really complicated at the proc-macro level, because we don't have full type info. The best we might do is some heuristic guessing.

> So now I'm wondering if there is a way to have a macro that transforms a standard Iterator fold into a Rayon fold+reduce generically, so the eventual result is the same in either case.

I have a different crate that kind of does this -- [`rayon-cond`](https://crates.io/crates/rayon-cond) -- but this makes parallelism a runtime decision. Rather than synthesizing serial `fold` into `fold+reduce`, it just maps to a new `Once` iterator so it looks like Rayon's `fold` that produces an iterator too. So you would always write your code in the parallel Rayon style, and the serial side tries to match that.

You could certainly look at that crate to try and make something that uses build conditions instead. I think that would be a bit awkward to design an API around this though -- e.g. should this build-conditional `map` alternate between returning `std::iter::Map` or `rayon::iter::Map`, or should it return its own `Map` that hides the difference internally? The latter is probably better, but it's a lot of work to provide a bunch of new wrapper types.

**Comment by bbarker** [comment]
Thanks, that gives me a lot to work with. I think I'll table this in a branch for now as it was something I was exploring and may come back to later once I actually need parallel code 😅 Still, it is good to see what should be possible with a little extra work.

Thanks again for all the pointers, this will be great.
